version: '3.8'
services:
  db:
    container_name: postgresDB
    image: postgres:15
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data
      - ./dbDump:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - db
    build: ./
    command: ./avitoIntershipBackend
    restart: on-failure
    ports:
      - $GO_LOCAL_PORT:$GO_DOCKER_PORT
    stdin_open: true
    tty: true
volumes:
  db:
    driver: local
